# Configurations
title:            Home
longtitle:        Strategi Network Disaggregation dengan Cassini dan DCSG
author:           A. Kiflan Jiyaad Mafazi & Muhammad Rizki Akbar
description: >
  Build Jekyll documentation site with the GitBook style.

version:          1.0
gitbook_version:  3.2.3

url: 'https://kippun.github.io'
baseurl: ''
rss:              RSS

remote_theme: sighingnow/jekyll-gitbook

toc:
  enabled: true
  h_min:   1
  h_max:   3

favicon_path:     assets/gitbook/images/cattos.ico

markdown:         kramdown
kramdown:
  auto_ids:               true
  input:                  GFM
  math_engine:            mathjax
  smart_quotes:           lsquo,rsquo,ldquo,rdquo
  toc_levels:             1..6
  syntax_highlighter:     rouge
  syntax_highlighter_opts:
    guess_lang:           true

syntax_highlighter_style: colorful

markdown_ext:             markdown,mkdown,mkdn,mkd,md

# Permalinks
permalink:                /:title.html
# Disqus comments
# disqushandler:            sighingnow

exclude:
  - _drafts

collections:
  fundamentals:
    output: true
    sort_by: order
    permalink: /:collection/:path/
  software:
    output: true
    sort_by: order
    permalink: /:collection/:path/
  hardware:
    output: true
    sort_by: order
    permalink: /:collection/:path/
  summary:
    output: true
    sort_by: order
    permalink: /:collection/:path/
  other:
    output: true
    sort_by: order
    permalink: /:collection/:path/

ordered_collections:
  - fundamentals
  - software
  - hardware
  - summary
  - other

page_width: 800px

destination:      ./_site
incremental:      false
regenerate:       true

plugins:
  - jekyll-feed
  - jekyll-readme-index
  - jemoji